"""Subset a local licensed Korean font for the offline SD interface.

Usage: python tools/embed-sd-fonts.py [font-file] [collection-index]
The default is Debian's Noto Sans CJK KR collection. No downloads are needed.
"""
import base64
import io
from pathlib import Path
import sys
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
source = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc'
index = int(sys.argv[2]) if len(sys.argv) > 2 else 1
text = set(chr(c) for c in range(32, 127))
for folder in ('data', 'js'):
    for file in (root / folder).glob('*.js'):
        text.update(file.read_text(encoding='utf-8'))
text.update((root / 'css/sd-theme.css').read_text(encoding='utf-8'))
text.update('天外')   # 40단계: 시작 화면 붉은 인장(코드에는 &#…; 로 쓴다)
def woff(path, number):
    font = TTFont(path, fontNumber=number)
    options = subset.Options()
    options.layout_features = ['*']
    subsetter = subset.Subsetter(options)
    subsetter.populate(text=''.join(text))
    subsetter.subset(font)
    # WOFF needs only zlib; the runtime does not require Brotli or a network font.
    font.flavor = 'woff'
    buffer = io.BytesIO()
    font.save(buffer)
    return buffer.getvalue()

sans = woff(source, index)
css = ("/* Noto Sans CJK KR · Noto Serif CJK KR, SIL OFL 1.1. Generated by tools/embed-sd-fonts.py. */\n"
       "@font-face { font-family:'SD Sans'; font-style:normal; font-weight:400; font-display:swap; "
       "src:url(data:font/woff;base64," + base64.b64encode(sans).decode('ascii') + ") format('woff'); }\n")
# Step 40 (Claude): serif titles from the approved mockups. Same OFL family; skipped if the font is not installed.
serif_path = Path(source).with_name('NotoSerifCJK-Bold.ttc')
if serif_path.exists():
    serif = woff(str(serif_path), index)
    css += ("@font-face { font-family:'SD Serif'; font-style:normal; font-weight:700; font-display:swap; "
            "src:url(data:font/woff;base64," + base64.b64encode(serif).decode('ascii') + ") format('woff'); }\n")
    print('Embedded SD serif font:', len(serif), 'bytes')
(root / 'css/sd-fonts.css').write_text(css, encoding='utf-8')
print('Embedded SD font:', len(sans), 'bytes')
