"""Subset a local licensed Korean font for the offline SD interface.

Usage: python tools/embed-sd-fonts.py [font-file] [collection-index]
The default is Debian's Noto Sans CJK KR collection. No downloads are needed.
"""
import base64
import io
from pathlib import Path
import sys
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
source = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc'
index = int(sys.argv[2]) if len(sys.argv) > 2 else 1
font = TTFont(source, fontNumber=index)
text = set(chr(c) for c in range(32, 127))
for folder in ('data', 'js'):
    for file in (root / folder).glob('*.js'):
        text.update(file.read_text(encoding='utf-8'))
text.update((root / 'css/sd-theme.css').read_text(encoding='utf-8'))
options = subset.Options()
options.layout_features = ['*']
subsetter = subset.Subsetter(options)
subsetter.populate(text=''.join(text))
subsetter.subset(font)
# WOFF needs only zlib; the runtime does not require Brotli or a network font.
font.flavor = 'woff'
buffer = io.BytesIO()
font.save(buffer)
encoded = base64.b64encode(buffer.getvalue()).decode('ascii')
(root / 'css/sd-fonts.css').write_text(
    "/* Noto Sans CJK KR, SIL OFL 1.1. Generated by tools/embed-sd-fonts.py. */\n"
    "@font-face { font-family:'SD Sans'; font-style:normal; font-weight:400; font-display:swap; "
    "src:url(data:font/woff;base64," + encoded + ") format('woff'); }\n", encoding='utf-8')
print('Embedded SD font:', len(buffer.getvalue()), 'bytes')
